# -*- coding: utf-8 -*-
"""final proj.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lrE8QGd4Ev298J06_VexbGVNz_5wq_5a

#Importing libraries
"""

import os
import numpy as np
import tensorflow as tf
from keras.utils import to_categorical
import tensorflow as tf
from tensorflow.keras.optimizers import Adam
import matplotlib.pyplot as plt
import seaborn as sns
import keras
from keras.models import Sequential
from keras.layers import Dense, Conv2D , MaxPool2D , Flatten , Dropout 
from keras.preprocessing.image import ImageDataGenerator
from keras.optimizers import Adam, RMSprop, Adagrad
from keras.layers import BatchNormalization
from sklearn.metrics import classification_report,confusion_matrix
import tensorflow as tf
import cv2
os.environ["KMP_DUPLICATE_LIB_OK"]="TRUE"
import numpy as np
import warnings
warnings.filterwarnings('ignore')
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

"""#Loading the Dataset and Assigning Validation Set"""

X_test1=np.load('drive/Othercomputers/My Laptop/final proj/task1 scene level 1/task1_X_test.npy',mmap_mode='r')
y_test1=np.load('drive/Othercomputers/My Laptop/final proj/task1 scene level 1/task1_y_test.npy',mmap_mode='r')
X_train1=np.load('drive/Othercomputers/My Laptop/final proj/drivetask/task1_X_train.npy',mmap_mode='r')
y_train1=np.load('drive/Othercomputers/My Laptop/final proj/task1 scene level 1/task1_y_train.npy',mmap_mode='r')

X_test2=np.load('drive/Othercomputers/My Laptop/final proj/task2_damage_state_1/task2_X_test.npy',mmap_mode='r')
y_test2=np.load('drive/Othercomputers/My Laptop/final proj/task2_damage_state_1/task2_y_test.npy',mmap_mode='r')
X_train2=np.load('drive/Othercomputers/My Laptop/final proj/drivetask/task2_X_train.npy',mmap_mode='r')
y_train2=np.load('drive/Othercomputers/My Laptop/final proj/task2_damage_state_1/task2_y_train.npy',mmap_mode='r')

X_test3=np.load('drive/Othercomputers/My Laptop/final proj/drivetask/task3_X_test.npy',mmap_mode='r')
y_test3=np.load('drive/Othercomputers/My Laptop/final proj/task3/task3_y_test.npy',mmap_mode='r')
X_train3=np.load('drive/Othercomputers/My Laptop/final proj/drivetask/task3_X_train.npy',mmap_mode='r')
y_train3=np.load('drive/Othercomputers/My Laptop/final proj/task3/task3_y_train.npy',mmap_mode='r')

X_test4=np.load('drive/Othercomputers/My Laptop/final proj/task4/task4_X_test.npy',mmap_mode='r')
y_test4=np.load('drive/Othercomputers/My Laptop/final proj/task4/task4_y_test.npy',mmap_mode='r')
X_train4=np.load('drive/Othercomputers/My Laptop/final proj/drivetask/task4_X_train.npy',mmap_mode='r')
y_train4=np.load('drive/Othercomputers/My Laptop/final proj/task4/task4_y_train.npy',mmap_mode='r')

X_test5=np.load('drive/Othercomputers/My Laptop/final proj/task5/task5_X_test.npy',mmap_mode='r')
y_test5=np.load('drive/Othercomputers/My Laptop/final proj/task5/task5_y_test.npy',mmap_mode='r')
X_train5=np.load('drive/Othercomputers/My Laptop/final proj/task5/task5_X_train.npy',mmap_mode='r')
y_train5=np.load('drive/Othercomputers/My Laptop/final proj/task5/task5_y_train.npy',mmap_mode='r')

X_test6=np.load('drive/Othercomputers/My Laptop/final proj/task6/task6_X_test.npy',mmap_mode='r')
y_test6=np.load('drive/Othercomputers/My Laptop/final proj/task6/task6_y_test.npy',mmap_mode='r')
X_train6=np.load('drive/Othercomputers/My Laptop/final proj/task6/task6_X_train.npy',mmap_mode='r')
y_train6=np.load('drive/Othercomputers/My Laptop/final proj/task6/task6_y_train.npy',mmap_mode='r')

X_test7=np.load('drive/Othercomputers/My Laptop/final proj/task7/task7_X_test.npy',mmap_mode='r')
y_test7=np.load('drive/Othercomputers/My Laptop/final proj/task7/task7_y_test.npy',mmap_mode='r')
X_train7=np.load('drive/Othercomputers/My Laptop/final proj/task7/task7_X_train.npy',mmap_mode='r')
y_train7=np.load('drive/Othercomputers/My Laptop/final proj/task7/task7_y_train.npy',mmap_mode='r')

X_test8=np.load('drive/Othercomputers/My Laptop/final proj/task8/task8_X_test.npy',mmap_mode='r')
y_test8=np.load('drive/Othercomputers/My Laptop/final proj/task8/task8_y_test.npy',mmap_mode='r')
X_train8=np.load('drive/Othercomputers/My Laptop/final proj/task8/task8_X_train.npy',mmap_mode='r')
y_train8=np.load('drive/Othercomputers/My Laptop/final proj/task8/task8_y_train.npy',mmap_mode='r')

X_train1, X_val1, y_train1, y_val1 = train_test_split(X_train1, y_train1, test_size=0.25, random_state=42)
X_train2, X_val2, y_train2, y_val2 = train_test_split(X_train2, y_train2, test_size=0.25, random_state=42)
X_train3, X_val3, y_train3, y_val3 = train_test_split(X_train3, y_train3, test_size=0.25, random_state=42)
X_train4, X_val4, y_train4, y_val4 = train_test_split(X_train4, y_train4, test_size=0.25, random_state=42)
X_train5, X_val5, y_train5, y_val5 = train_test_split(X_train5, y_train5, test_size=0.25, random_state=42)
X_train6, X_val6, y_train6, y_val6 = train_test_split(X_train6, y_train6, test_size=0.25, random_state=42)
X_train7, X_val7, y_train7, y_val7 = train_test_split(X_train7, y_train7, test_size=0.25, random_state=42)
X_train8, X_val8, y_train8, y_val8 = train_test_split(X_train8, y_train8, test_size=0.25, random_state=42)
X_val1, y_val1=X_val1/255.0,y_val1/255.0
X_val2, y_val2=X_val2/255.0,y_val2/255.0
X_val3, y_val3=X_val3/255.0,y_val3/255.0
X_val4, y_val4=X_val4/255.0,y_val4/255.0
X_val5, y_val5=X_val5/255.0,y_val5/255.0
X_val6, y_val6=X_val6/255.0,y_val6/255.0
X_val7, y_val7=X_val7/255.0,y_val7/255.0
X_val8, y_val8=X_val8/255.0,y_val8/255.0